# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Use a package of configuration called an orb.
jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: installing 
          command:
            sudo apt-get update;
            sudo apt install python3-pip;
            sudo pip3 install awsebcli --upgrade;
      - run:
          name: aws role  
          command: |
            aws sts assume-role --role-arn arn:aws:iam::131125430978:role/Administrators --role-session-name tamir
      - run: cd ./app && npm install #&& npm run build
      - run: aws s3 sync ./app s3://tamir-ci-cd-demo

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
